# Generated by Django 2.0.4 on 2018-04-27 14:59

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180427_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.contrib.auth.models.User, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
