# Generated by Django 2.0.4 on 2018-04-29 10:30

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180427_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='whatsapp',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
