# Generated by Django 2.0.4 on 2018-05-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180429_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(blank=True, upload_to='accounts/static/profile_pic'),
        ),
    ]
