# Generated by Django 2.0.4 on 2018-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180511_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='static/profile.png', upload_to='profile/profile_pic'),
        ),
    ]
