# Generated by Django 2.0.4 on 2018-09-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20180904_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='/static/profile.png', upload_to='profile/profile_pic'),
        ),
    ]
