# Generated by Django 2.0.4 on 2018-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20180904_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.ImageField(default='//free_lan/media/profile.png', upload_to='profile/profile_pic'),
        ),
    ]
