# Generated by Django 2.0.4 on 2018-09-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20180911_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Grender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
            preserve_default=False,
        ),
    ]
