# Generated by Django 2.0.4 on 2018-09-12 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20180912_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='specialty',
        ),
    ]
