# Generated by Django 2.0.4 on 2018-09-12 11:31

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_userprofile_specialty'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=multiselectfield.db.fields.MultiSelectField(default='other', max_length=200),
            preserve_default=False,
        ),
    ]
