# Generated by Django 2.0.4 on 2018-09-12 11:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20180912_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
