# Generated by Django 2.0.4 on 2018-09-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20180912_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='are you sure ',
            field=models.BooleanField(default=False),
        ),
    ]
