# Generated by Django 2.0.4 on 2018-09-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_userprofile_are you sure '),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='are you sure ',
        ),
    ]
