# Generated by Django 2.0.4 on 2018-09-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_remove_userprofile_are you sure '),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='are you sure'),
        ),
    ]
