# Generated by Django 2.0.4 on 2018-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_userprofile_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Enable employer to see my private data like (phone,whatsapp,..etc)'),
        ),
    ]
