# Generated by Django 2.0.4 on 2018-09-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20180918_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_lancer',
            field=models.BooleanField(default=False, verbose_name='iclude me in free lancer lists'),
        ),
    ]
