# Generated by Django 2.0.4 on 2018-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_userprofile_free_lancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='free_lancer',
            field=models.BooleanField(default=False, verbose_name='Include me in free lancer lists'),
        ),
    ]
