# Generated by Django 2.0.4 on 2018-07-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertis', '0003_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='age',
            field=models.IntegerField(),
        ),
    ]
