# Generated by Django 2.0.4 on 2018-09-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Advertis', '0004_auto_20180723_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
