# Generated by Django 2.0.4 on 2018-09-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertis', '0006_auto_20180911_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='adver_m',
            name='status',
            field=models.CharField(choices=[('P', 'puplished'), ('U', 'under revision')], default='P', max_length=1),
        ),
    ]
