# Generated by Django 2.0.4 on 2018-09-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Advertis', '0007_adver_m_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adver_m',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('waiting admin approval', 'waiting admin approval')], default='waiting admin approval', max_length=20),
        ),
    ]
